### ISSUE TITLE
ci: Clean up current codebase with `clang-tidy`

### ISSUE THREAD

**Issue by SdtElectronics** [zephyrproject-rtos/gsoc-2022-thrift#102]
As `clang-tidy` related work will be dealt later, this is separated from #100 .

As a separate commit in the same PR, add a ci workflow that runs clang-tidy

GanttStart: 2022-09-01
GanttDue: 2022-09-04

**Comment by cfriedt** [comment]
Closing, as this will be more of a general upstream concern
