### ISSUE TITLE
ZlibTransport integration

### ISSUE THREAD

**Issue by SdtElectronics** [zephyrproject-rtos/gsoc-2022-thrift#91]
This should be a reimplementation of the upstream ZlibTransport, but without Zlib itself. Zlib is likely too large to include on most microcontrollers and the API is not ideal. 

To that end, we consider the actual compressor / decompressor an implementation detail that should be hidden behind the ZlibTransport interface. Eventually, if Zephyr chooses to provide an internal library for compression / decompression, this implementation could be moved there.

Subtasks include:
- [x] Add Kconfig entries to enable and configure ZlibTransport (maybe specify buffer sizes / compression ratios as sub-options)
- [x] Add `CMakeLists.txt` entries to conditionally build ZlibTransport
- [x] Create an implementation of the deflate algorithm suitable for Zephyr (compress / decompress, under e.g. `lib/deflate`)
- [x] Add tests for the deflate algorithm (e.g. under `tests/lib/deflate`)
- [x] Implement the ZlibTransport interface using the local deflate algorithm
- [x] Create Thrift tests (leveraging .thrift files added in #92)
- [x] Add `Makefile`s so that client / server samples can be easily built for the host with the native Thrift libraries

See also https://datatracker.ietf.org/doc/html/rfc1951

GanttStart: 2022-07-15
GanttDue: 2022-07-31

**Comment by cfriedt** [comment]
See also https://datatracker.ietf.org/doc/html/rfc1951

**Comment by SdtElectronics** [comment]
#123 will provide preliminary support to ZlibTransport, but there are problems should be addressed later:
* The underlying deflate implementation uses an inefficient output mechanism which incurred massive reallocation and copying. A new output buffering method has to be implemented in place of it.
* The inflate implementation currently allocates a huge 32kB buffer for remembering the output, which is unnecessary for some conditions. It should replaced by a scalable buffer in the future.
